/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EE333;

/**
 *
 * @author Josh Yates
 */
public class EmployeeJPanel extends javax.swing.JPanel {
    private Employee employee;
    private String ID;
    private String firstName;
    private String lastName;
    private Status status;
    
    public void Employee(String ID, String firstName, String lastName, Status status)
    {
        this.ID = ID;
        this.firstName = firstName;
        this.lastName = lastName;
        this.status = status;
    }
    /**
     * Creates new form EmployeeJPanel
     */
    public EmployeeJPanel() {
        initComponents();
        
        java.io.File inputFile;
        java.io.FileReader InputFileReader;
        java.io.BufferedReader InputBufferedReader;
        String line = "";
        
    }
    
    //this comes from gui video 4
//    public boolean exportCustom() {
//        boolean results = true;
//        java.io.File outputFile;
//        //leverage our id --> id.user
//        // asssumes a valid user(null .status = incomplete)
//        if (this.employee == null) {
//            // then do nothing
//            results = false;
//        } else if (this.employee.getStatus() == EE333.Status.incomplete) {
//            //do nothing
//            results = false;
//        } else {
//            //colect the information from the gui before exporting
//            this.employee.setID(this.jTextFieldID.getText());
//            this.employee.setFirstName(this.jTextFieldID.getText());
//            this.employee.setLastName(this.jTextFieldID.getText());
//            //should check if status is active
//            
//            outputFile = new java.io.File( this.employee.getID() + ".employee");
//            results = exportCustom(outputFile);
//        }
//        
//        return(results);
//    }
//    
//    //this comes from gui video 4
//    public boolean exportCustom(java.io.File outputFile ) {
//        boolean results = true;
//        java.io.FileWriter outputFileWriter;
//        
//        try {
//            outputFileWriter = new java.io.FileWriter(outputFile);
//           // outputFileWriter.append( this.employee.exportCustom());
//            outputFileWriter.close();
//        } catch (java.lang.Exception ex) {
//            System.out.println( ex.toString() );
//        }
//        
//        
//        
//        return results;
//    }
//    
//    
//    
//    //this comes from video guiwrapper3
//    public boolean importCustom( String vinNumber ) {
//        boolean results = true;
//        
//        
//        this.employee = new EE333.Employee.importEmployeeInfo(customString);
//        if (this.employee.getStatus() == EE333.Status.incomplete) {
//            this.jTextFieldID.setText("");
//            this.jTextFieldFirstName.setText("");
//            this.jLabelLastName.setText("");
//            results = false;
//        } else {
//            //we need to update our gui
//            this.jTextFieldID.setText(this.ID.getID());
//            this.jTextFieldFirstName.setText(this.firstName.getFirstName());
//            this.jLabelLastName.setText(this.lastName.getLastName());
//            results = true;
//        }
//        
//        return(results);
//    }
//    
//
//     
//     //this function was used in the video guiwrapper3
//     private String importString ( java.io.File stringFile ) {
//         String results = "";
//         String line = "";
//         java.io.FileReader inputFileReader;
//         java.io.BufferedReader inputBufferedReader;
//         
//         try {
//             if(inputFile.exists() == true) {
//             inputFileReader = new java.io.FileReader(inputFileReader);
//             inputBufferedReader = new java.io.BufferedReader(inputFileReader);
//             
//             while((line = inputBufferedReader.readLine()) != null) {
//                 results += line + '\n'; //appends contents line by line
//             }
//             
//             inputBufferedReader.close();
//         }
//         } catch (java.lang.Exception ex) {
//             System.out.println( ex.toString());
//         }
//         
//         return(results);
//     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();

        jLabelID.setText("ID:");

        jLabelPassword.setText("Password:");

        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPassword;
    // End of variables declaration//GEN-END:variables
}
