
import javax.swing.JTextField;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;



/**
 *
 * @author roman
 */
public class Delivery_NotificationJFrame extends javax.swing.JFrame {

   JTextField dateText;

    /**
     * Creates new form Delivery_NotificationJFrame
     */
    public Delivery_NotificationJFrame() {
        initComponents();
    
    
        // Setting Text boxes in empty border JPanel
        dateText = new JTextField("");
        
        Notification.add(dateText);
        //pack();
        Notification.setVisible(true);
        
        
        
        // Will set up local time and date here
        // Setting up Variables here
        LocalDate currentDate = LocalDate.now();
        LocalTime currentTime = LocalTime.now();
        LocalDateTime currentDateTime = LocalDateTime.now();
        
        // Formating Date variables into a string
        DateTimeFormatter dtf = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT);
        String currentDateFormatted = dtf.format(currentDate); 
        
        // Formating Time variables into a string
        DateTimeFormatter ttf = DateTimeFormatter.ofLocalizedTime(FormatStyle.MEDIUM);
        String currentTimeFormatted = ttf.format(currentTime);
        
        // Making Date and Time text box read-only
        dateText.setEditable(false); 
        
        // Setting Date and Time in text box
        dateText.setText(currentDateFormatted);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonClose = new javax.swing.JButton();
        Notification = new javax.swing.JPanel();
        Notifcation2 = new javax.swing.JPanel();
        Notification3 = new javax.swing.JPanel();
        delivery_NotificationJPanel1 = new Delivery_NotificationJPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonClose.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        Notification.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Notification.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Notification.setPreferredSize(new java.awt.Dimension(700, 350));
        Notification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotificationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NotificationLayout = new javax.swing.GroupLayout(Notification);
        Notification.setLayout(NotificationLayout);
        NotificationLayout.setHorizontalGroup(
            NotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        NotificationLayout.setVerticalGroup(
            NotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        Notifcation2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Notifcation2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Notifcation2.setPreferredSize(new java.awt.Dimension(700, 350));
        Notifcation2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Notifcation2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Notifcation2Layout = new javax.swing.GroupLayout(Notifcation2);
        Notifcation2.setLayout(Notifcation2Layout);
        Notifcation2Layout.setHorizontalGroup(
            Notifcation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        Notifcation2Layout.setVerticalGroup(
            Notifcation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        Notification3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Notification3.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        Notification3.setPreferredSize(new java.awt.Dimension(700, 350));
        Notification3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Notification3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Notification3Layout = new javax.swing.GroupLayout(Notification3);
        Notification3.setLayout(Notification3Layout);
        Notification3Layout.setHorizontalGroup(
            Notification3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        Notification3Layout.setVerticalGroup(
            Notification3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delivery_NotificationJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Notification3, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notifcation2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(delivery_NotificationJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Notification, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Notification3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Notifcation2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void NotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationMouseClicked

        DeliveryJFrame deliveryjframe;

        deliveryjframe = new DeliveryJFrame();
        deliveryjframe.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_NotificationMouseClicked

    private void Notifcation2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Notifcation2MouseClicked

        DeliveryJFrame deliveryjframe;

        deliveryjframe = new DeliveryJFrame();
        deliveryjframe.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_Notifcation2MouseClicked

    private void Notification3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Notification3MouseClicked

        DeliveryJFrame deliveryjframe;

        deliveryjframe = new DeliveryJFrame();
        deliveryjframe.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_Notification3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery_NotificationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery_NotificationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery_NotificationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery_NotificationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delivery_NotificationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Notifcation2;
    private javax.swing.JPanel Notification;
    private javax.swing.JPanel Notification3;
    private Delivery_NotificationJPanel delivery_NotificationJPanel1;
    private javax.swing.JButton jButtonClose;
    // End of variables declaration//GEN-END:variables
}
